version: '3.8'

services:

  db:
    image: postgres:15-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  broker:
    image: redis
    restart: always

  web:
    build:
      context: ../project/
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ../project/project/.env
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate && 
             python3 manage.py autocreatesuperuser &&
             python3 manage.py runserver 0.0.0.0:8000"

  worker:
    restart: always
    build:
      context: ../project/
    depends_on:
      - db
    env_file:
      - ../project/project/.env
    command: ['celery', '--workdir=./', '-A', 'project', 'worker']

  celery-beat:
    restart: always
    build:
      context: ../project/
    depends_on:
      - db
    env_file:
      - ../project/project/.env
    command: ['celery', '--workdir=./', '-A', 'project', 'beat', '-l', 'INFO', '--scheduler', 'django_celery_beat.schedulers:DatabaseScheduler']

volumes:
  db: